#! /bin/bash

set -u
set -e

script_name=${0##*/}

die() {
    echo -e "${script_name} - Error: ${1:-}" >&2
    exit 1
}

usage() {
    [[ -z "${1:-}" ]] || echo -e "Error: ${1}\n" >&2
    grep '^#/' $0 | cut -c 4- | sed \
        -e "s/@PROGRAM@/${script_name}/g" >&2
    exit 1;
}

call_api() {
  curl -s $@ -H 'Pragma: no-cache' -H 'App-Key: f0bc4f65f4fbfe7b4b3b7264b655f5eb' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,fr;q=0.7' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Accept: application/hal+json,application/json' -H 'Cache-Control: no-cache' -H 'App-Id: f6b16c23' -H 'Connection: keep-alive' --compressed
}
