#! /bin/bash

##
#/
#/ @PROGRAM@ can be used to list Nuffield Health classes for a specific date.
#/
#/ Usage:
#/
#/ @PROGRAM@ -d <date> [OPTIONS]
#/
#/ OPTIONS:
#/
#/     -b   include only bookable classes
#/
#/ Example:
#/
#/     @PROGRAM@ -d "2019-01-13"
#/
##

where_am_i="${0%/*}"
source "${where_am_i}/common"

input_date=""
include_non_bookable="true"
while getopts "bd:h" option_name; do
    case $option_name in
        d) input_date="${OPTARG:-}";;
        b) include_non_bookable="false";;
        h) usage;;
    esac
done

[[ -n "${input_date}" ]] ||
    usage "Please specify the date with -d"

call_api "https://nuffield.bookingbug.com/api/v1/37159/events?start_date=${input_date}&end_date=${input_date}&per_page=600&embed=person&include_non_bookable=${include_non_bookable}" | jq '._embedded.events | map( { (.id|tostring): {id, event_chain_id, datetime, description, duration, num_spaces, spaces_booked, spaces_wait, bookable} }) | add | [.[]]' | less
